pub mod description_printer;
mod rgb;

use rgb::SimilarityCalculator;
use std::cmp::Ordering;

#[derive(Debug)]
pub struct Color {
    pub name: &'static str,
    pub hex: &'static str,
}

trait ColorConvertable {
    fn rgb(&self) -> rgb::RGB;
}

impl ColorConvertable for Color {
    fn rgb(&self) -> rgb::RGB {
        return parse_hex(self.hex).unwrap();
    }
}

impl SimilarityCalculator<Color> for Color {
    fn similarity(&self, other: &Color) -> f64 {
        return self.rgb().similarity(&other.rgb());
    }
}

macro_rules! color {
    ($hex:expr, $name:expr) => {{
        Color {
            name: $name,
            hex: $hex,
        }
    }};
}

pub fn parse_hex(hex: &str) -> Result<rgb::RGB, ()> {
    let hex_without_prefix: String = match hex.strip_prefix("#") {
        Some(hex) => String::from(hex),
        None => String::from(hex),
    };

    return rgb::parse_hash(hex_without_prefix.as_bytes());
}

pub fn find_closest_match(rgb: &rgb::RGB) -> &'static Color {
    return COLORS
        .iter()
        .max_by(|color, other_color| {
            let a = color.rgb().similarity(rgb);
            let b = other_color.rgb().similarity(rgb);

            if a == b {
                return Ordering::Equal;
            } else if a > b {
                return Ordering::Greater;
            } else {
                return Ordering::Less;
            }
        })
        .unwrap();
}

const COLORS: [Color; 1566] = [
    color!("#000000", "Black"),
    color!("#000080", "Navy Blue"),
    color!("#0000C8", "Dark Blue"),
    color!("#0000FF", "Blue"),
    color!("#000741", "Stratos"),
    color!("#001B1C", "Swamp"),
    color!("#002387", "Resolution Blue"),
    color!("#002900", "Deep Fir"),
    color!("#002E20", "Burnham"),
    color!("#002FA7", "International Klein Blue"),
    color!("#003153", "Prussian Blue"),
    color!("#003366", "Midnight Blue"),
    color!("#003399", "Smalt"),
    color!("#003532", "Deep Teal"),
    color!("#003E40", "Cyprus"),
    color!("#004620", "Kaitoke Green"),
    color!("#0047AB", "Cobalt"),
    color!("#004816", "Crusoe"),
    color!("#004950", "Sherpa Blue"),
    color!("#0056A7", "Endeavour"),
    color!("#00581A", "Camarone"),
    color!("#0066CC", "Science Blue"),
    color!("#0066FF", "Blue Ribbon"),
    color!("#00755E", "Tropical Rain Forest"),
    color!("#0076A3", "Allports"),
    color!("#007BA7", "Deep Cerulean"),
    color!("#007EC7", "Lochmara"),
    color!("#007FFF", "Azure Radiance"),
    color!("#008080", "Teal"),
    color!("#0095B6", "Bondi Blue"),
    color!("#009DC4", "Pacific Blue"),
    color!("#00A693", "Persian Green"),
    color!("#00A86B", "Jade"),
    color!("#00CC99", "Caribbean Green"),
    color!("#00CCCC", "Robin's Egg Blue"),
    color!("#00FF00", "Green"),
    color!("#00FF7F", "Spring Green"),
    color!("#00FFFF", "Cyan / Aqua"),
    color!("#010D1A", "Blue Charcoal"),
    color!("#011635", "Midnight"),
    color!("#011D13", "Holly"),
    color!("#012731", "Daintree"),
    color!("#01361C", "Cardin Green"),
    color!("#01371A", "County Green"),
    color!("#013E62", "Astronaut Blue"),
    color!("#013F6A", "Regal Blue"),
    color!("#014B43", "Aqua Deep"),
    color!("#015E85", "Orient"),
    color!("#016162", "Blue Stone"),
    color!("#016D39", "Fun Green"),
    color!("#01796F", "Pine Green"),
    color!("#017987", "Blue Lagoon"),
    color!("#01826B", "Deep Sea"),
    color!("#01A368", "Green Haze"),
    color!("#022D15", "English Holly"),
    color!("#02402C", "Sherwood Green"),
    color!("#02478E", "Congress Blue"),
    color!("#024E46", "Evening Sea"),
    color!("#026395", "Bahama Blue"),
    color!("#02866F", "Observatory"),
    color!("#02A4D3", "Cerulean"),
    color!("#03163C", "Tangaroa"),
    color!("#032B52", "Green Vogue"),
    color!("#036A6E", "Mosque"),
    color!("#041004", "Midnight Moss"),
    color!("#041322", "Black Pearl"),
    color!("#042E4C", "Blue Whale"),
    color!("#044022", "Zuccini"),
    color!("#044259", "Teal Blue"),
    color!("#051040", "Deep Cove"),
    color!("#051657", "Gulf Blue"),
    color!("#055989", "Venice Blue"),
    color!("#056F57", "Watercourse"),
    color!("#062A78", "Catalina Blue"),
    color!("#063537", "Tiber"),
    color!("#069B81", "Gossamer"),
    color!("#06A189", "Niagara"),
    color!("#073A50", "Tarawera"),
    color!("#080110", "Jaguar"),
    color!("#081910", "Black Bean"),
    color!("#082567", "Deep Sapphire"),
    color!("#088370", "Elf Green"),
    color!("#08E8DE", "Bright Turquoise"),
    color!("#092256", "Downriver"),
    color!("#09230F", "Palm Green"),
    color!("#09255D", "Madison"),
    color!("#093624", "Bottle Green"),
    color!("#095859", "Deep Sea Green"),
    color!("#097F4B", "Salem"),
    color!("#0A001C", "Black Russian"),
    color!("#0A480D", "Dark Fern"),
    color!("#0A6906", "Japanese Laurel"),
    color!("#0A6F75", "Atoll"),
    color!("#0B0B0B", "Cod Gray"),
    color!("#0B0F08", "Marshland"),
    color!("#0B1107", "Gordons Green"),
    color!("#0B1304", "Black Forest"),
    color!("#0B6207", "San Felix"),
    color!("#0BDA51", "Malachite"),
    color!("#0C0B1D", "Ebony"),
    color!("#0C0D0F", "Woodsmoke"),
    color!("#0C1911", "Racing Green"),
    color!("#0C7A79", "Surfie Green"),
    color!("#0C8990", "Blue Chill"),
    color!("#0D0332", "Black Rock"),
    color!("#0D1117", "Bunker"),
    color!("#0D1C19", "Aztec"),
    color!("#0D2E1C", "Bush"),
    color!("#0E0E18", "Cinder"),
    color!("#0E2A30", "Firefly"),
    color!("#0F2D9E", "Torea Bay"),
    color!("#10121D", "Vulcan"),
    color!("#101405", "Green Waterloo"),
    color!("#105852", "Eden"),
    color!("#110C6C", "Arapawa"),
    color!("#120A8F", "Ultramarine"),
    color!("#123447", "Elephant"),
    color!("#126B40", "Jewel"),
    color!("#130000", "Diesel"),
    color!("#130A06", "Asphalt"),
    color!("#13264D", "Blue Zodiac"),
    color!("#134F19", "Parsley"),
    color!("#140600", "Nero"),
    color!("#1450AA", "Tory Blue"),
    color!("#151F4C", "Bunting"),
    color!("#1560BD", "Denim"),
    color!("#15736B", "Genoa"),
    color!("#161928", "Mirage"),
    color!("#161D10", "Hunter Green"),
    color!("#162A40", "Big Stone"),
    color!("#163222", "Celtic"),
    color!("#16322C", "Timber Green"),
    color!("#163531", "Gable Green"),
    color!("#171F04", "Pine Tree"),
    color!("#175579", "Chathams Blue"),
    color!("#182D09", "Deep Forest Green"),
    color!("#18587A", "Blumine"),
    color!("#19330E", "Palm Leaf"),
    color!("#193751", "Nile Blue"),
    color!("#1959A8", "Fun Blue"),
    color!("#1A1A68", "Lucky Point"),
    color!("#1AB385", "Mountain Meadow"),
    color!("#1B0245", "Tolopea"),
    color!("#1B1035", "Haiti"),
    color!("#1B127B", "Deep Koamaru"),
    color!("#1B1404", "Acadia"),
    color!("#1B2F11", "Seaweed"),
    color!("#1B3162", "Biscay"),
    color!("#1B659D", "Matisse"),
    color!("#1C1208", "Crowshead"),
    color!("#1C1E13", "Rangoon Green"),
    color!("#1C39BB", "Persian Blue"),
    color!("#1C402E", "Everglade"),
    color!("#1C7C7D", "Elm"),
    color!("#1D6142", "Green Pea"),
    color!("#1E0F04", "Creole"),
    color!("#1E1609", "Karaka"),
    color!("#1E1708", "El Paso"),
    color!("#1E385B", "Cello"),
    color!("#1E433C", "Te Papa Green"),
    color!("#1E90FF", "Dodger Blue"),
    color!("#1E9AB0", "Eastern Blue"),
    color!("#1F120F", "Night Rider"),
    color!("#1FC2C2", "Java"),
    color!("#20208D", "Jacksons Purple"),
    color!("#202E54", "Cloud Burst"),
    color!("#204852", "Blue Dianne"),
    color!("#211A0E", "Eternity"),
    color!("#220878", "Deep Blue"),
    color!("#228B22", "Forest Green"),
    color!("#233418", "Mallard"),
    color!("#240A40", "Violet"),
    color!("#240C02", "Kilamanjaro"),
    color!("#242A1D", "Log Cabin"),
    color!("#242E16", "Black Olive"),
    color!("#24500F", "Green House"),
    color!("#251607", "Graphite"),
    color!("#251706", "Cannon Black"),
    color!("#251F4F", "Port Gore"),
    color!("#25272C", "Shark"),
    color!("#25311C", "Green Kelp"),
    color!("#2596D1", "Curious Blue"),
    color!("#260368", "Paua"),
    color!("#26056A", "Paris M"),
    color!("#261105", "Wood Bark"),
    color!("#261414", "Gondola"),
    color!("#262335", "Steel Gray"),
    color!("#26283B", "Ebony Clay"),
    color!("#273A81", "Bay of Many"),
    color!("#27504B", "Plantation"),
    color!("#278A5B", "Eucalyptus"),
    color!("#281E15", "Oil"),
    color!("#283A77", "Astronaut"),
    color!("#286ACD", "Mariner"),
    color!("#290C5E", "Violent Violet"),
    color!("#292130", "Bastille"),
    color!("#292319", "Zeus"),
    color!("#292937", "Charade"),
    color!("#297B9A", "Jelly Bean"),
    color!("#29AB87", "Jungle Green"),
    color!("#2A0359", "Cherry Pie"),
    color!("#2A140E", "Coffee Bean"),
    color!("#2A2630", "Baltic Sea"),
    color!("#2A380B", "Turtle Green"),
    color!("#2A52BE", "Cerulean Blue"),
    color!("#2B0202", "Sepia Black"),
    color!("#2B194F", "Valhalla"),
    color!("#2B3228", "Heavy Metal"),
    color!("#2C0E8C", "Blue Gem"),
    color!("#2C1632", "Revolver"),
    color!("#2C2133", "Bleached Cedar"),
    color!("#2C8C84", "Lochinvar"),
    color!("#2D2510", "Mikado"),
    color!("#2D383A", "Outer Space"),
    color!("#2D569B", "St Tropaz"),
    color!("#2E0329", "Jacaranda"),
    color!("#2E1905", "Jacko Bean"),
    color!("#2E3222", "Rangitoto"),
    color!("#2E3F62", "Rhino"),
    color!("#2E8B57", "Sea Green"),
    color!("#2EBFD4", "Scooter"),
    color!("#2F270E", "Onion"),
    color!("#2F3CB3", "Governor Bay"),
    color!("#2F519E", "Sapphire"),
    color!("#2F5A57", "Spectra"),
    color!("#2F6168", "Casal"),
    color!("#300529", "Melanzane"),
    color!("#301F1E", "Cocoa Brown"),
    color!("#302A0F", "Woodrush"),
    color!("#304B6A", "San Juan"),
    color!("#30D5C8", "Turquoise"),
    color!("#311C17", "Eclipse"),
    color!("#314459", "Pickled Bluewood"),
    color!("#315BA1", "Azure"),
    color!("#31728D", "Calypso"),
    color!("#317D82", "Paradiso"),
    color!("#32127A", "Persian Indigo"),
    color!("#32293A", "Blackcurrant"),
    color!("#323232", "Mine Shaft"),
    color!("#325D52", "Stromboli"),
    color!("#327C14", "Bilbao"),
    color!("#327DA0", "Astral"),
    color!("#33036B", "Christalle"),
    color!("#33292F", "Thunder"),
    color!("#33CC99", "Shamrock"),
    color!("#341515", "Tamarind"),
    color!("#350036", "Mardi Gras"),
    color!("#350E42", "Valentino"),
    color!("#350E57", "Jagger"),
    color!("#353542", "Tuna"),
    color!("#354E8C", "Chambray"),
    color!("#363050", "Martinique"),
    color!("#363534", "Tuatara"),
    color!("#363C0D", "Waiouru"),
    color!("#36747D", "Ming"),
    color!("#368716", "La Palma"),
    color!("#370202", "Chocolate"),
    color!("#371D09", "Clinker"),
    color!("#37290E", "Brown Tumbleweed"),
    color!("#373021", "Birch"),
    color!("#377475", "Oracle"),
    color!("#380474", "Blue Diamond"),
    color!("#381A51", "Grape"),
    color!("#383533", "Dune"),
    color!("#384555", "Oxford Blue"),
    color!("#384910", "Clover"),
    color!("#394851", "Limed Spruce"),
    color!("#396413", "Dell"),
    color!("#3A0020", "Toledo"),
    color!("#3A2010", "Sambuca"),
    color!("#3A2A6A", "Jacarta"),
    color!("#3A686C", "William"),
    color!("#3A6A47", "Killarney"),
    color!("#3AB09E", "Keppel"),
    color!("#3B000B", "Temptress"),
    color!("#3B0910", "Aubergine"),
    color!("#3B1F1F", "Jon"),
    color!("#3B2820", "Treehouse"),
    color!("#3B7A57", "Amazon"),
    color!("#3B91B4", "Boston Blue"),
    color!("#3C0878", "Windsor"),
    color!("#3C1206", "Rebel"),
    color!("#3C1F76", "Meteorite"),
    color!("#3C2005", "Dark Ebony"),
    color!("#3C3910", "Camouflage"),
    color!("#3C4151", "Bright Gray"),
    color!("#3C4443", "Cape Cod"),
    color!("#3C493A", "Lunar Green"),
    color!("#3D0C02", "Bean  "),
    color!("#3D2B1F", "Bistre"),
    color!("#3D7D52", "Goblin"),
    color!("#3E0480", "Kingfisher Daisy"),
    color!("#3E1C14", "Cedar"),
    color!("#3E2B23", "English Walnut"),
    color!("#3E2C1C", "Black Marlin"),
    color!("#3E3A44", "Ship Gray"),
    color!("#3EABBF", "Pelorous"),
    color!("#3F2109", "Bronze"),
    color!("#3F2500", "Cola"),
    color!("#3F3002", "Madras"),
    color!("#3F307F", "Minsk"),
    color!("#3F4C3A", "Cabbage Pont"),
    color!("#3F583B", "Tom Thumb"),
    color!("#3F5D53", "Mineral Green"),
    color!("#3FC1AA", "Puerto Rico"),
    color!("#3FFF00", "Harlequin"),
    color!("#401801", "Brown Pod"),
    color!("#40291D", "Cork"),
    color!("#403B38", "Masala"),
    color!("#403D19", "Thatch Green"),
    color!("#405169", "Fiord"),
    color!("#40826D", "Viridian"),
    color!("#40A860", "Chateau Green"),
    color!("#410056", "Ripe Plum"),
    color!("#411F10", "Paco"),
    color!("#412010", "Deep Oak"),
    color!("#413C37", "Merlin"),
    color!("#414257", "Gun Powder"),
    color!("#414C7D", "East Bay"),
    color!("#4169E1", "Royal Blue"),
    color!("#41AA78", "Ocean Green"),
    color!("#420303", "Burnt Maroon"),
    color!("#423921", "Lisbon Brown"),
    color!("#427977", "Faded Jade"),
    color!("#431560", "Scarlet Gum"),
    color!("#433120", "Iroko"),
    color!("#433E37", "Armadillo"),
    color!("#434C59", "River Bed"),
    color!("#436A0D", "Green Leaf"),
    color!("#44012D", "Barossa"),
    color!("#441D00", "Morocco Brown"),
    color!("#444954", "Mako"),
    color!("#454936", "Kelp"),
    color!("#456CAC", "San Marino"),
    color!("#45B1E8", "Picton Blue"),
    color!("#460B41", "Loulou"),
    color!("#462425", "Crater Brown"),
    color!("#465945", "Gray Asparagus"),
    color!("#4682B4", "Steel Blue"),
    color!("#480404", "Rustic Red"),
    color!("#480607", "Bulgarian Rose"),
    color!("#480656", "Clairvoyant"),
    color!("#481C1C", "Cocoa Bean"),
    color!("#483131", "Woody Brown"),
    color!("#483C32", "Taupe"),
    color!("#49170C", "Van Cleef"),
    color!("#492615", "Brown Derby"),
    color!("#49371B", "Metallic Bronze"),
    color!("#495400", "Verdun Green"),
    color!("#496679", "Blue Bayoux"),
    color!("#497183", "Bismark"),
    color!("#4A2A04", "Bracken"),
    color!("#4A3004", "Deep Bronze"),
    color!("#4A3C30", "Mondo"),
    color!("#4A4244", "Tundora"),
    color!("#4A444B", "Gravel"),
    color!("#4A4E5A", "Trout"),
    color!("#4B0082", "Pigment Indigo"),
    color!("#4B5D52", "Nandor"),
    color!("#4C3024", "Saddle"),
    color!("#4C4F56", "Abbey"),
    color!("#4D0135", "Blackberry"),
    color!("#4D0A18", "Cab Sav"),
    color!("#4D1E01", "Indian Tan"),
    color!("#4D282D", "Cowboy"),
    color!("#4D282E", "Livid Brown"),
    color!("#4D3833", "Rock"),
    color!("#4D3D14", "Punga"),
    color!("#4D400F", "Bronzetone"),
    color!("#4D5328", "Woodland"),
    color!("#4E0606", "Mahogany"),
    color!("#4E2A5A", "Bossanova"),
    color!("#4E3B41", "Matterhorn"),
    color!("#4E420C", "Bronze Olive"),
    color!("#4E4562", "Mulled Wine"),
    color!("#4E6649", "Axolotl"),
    color!("#4E7F9E", "Wedgewood"),
    color!("#4EABD1", "Shakespeare"),
    color!("#4F1C70", "Honey Flower"),
    color!("#4F2398", "Daisy Bush"),
    color!("#4F69C6", "Indigo"),
    color!("#4F7942", "Fern Green"),
    color!("#4F9D5D", "Fruit Salad"),
    color!("#4FA83D", "Apple"),
    color!("#504351", "Mortar"),
    color!("#507096", "Kashmir Blue"),
    color!("#507672", "Cutty Sark"),
    color!("#50C878", "Emerald"),
    color!("#514649", "Emperor"),
    color!("#516E3D", "Chalet Green"),
    color!("#517C66", "Como"),
    color!("#51808F", "Smalt Blue"),
    color!("#52001F", "Castro"),
    color!("#520C17", "Maroon Oak"),
    color!("#523C94", "Gigas"),
    color!("#533455", "Voodoo"),
    color!("#534491", "Victoria"),
    color!("#53824B", "Hippie Green"),
    color!("#541012", "Heath"),
    color!("#544333", "Judge Gray"),
    color!("#54534D", "Fuscous Gray"),
    color!("#549019", "Vida Loca"),
    color!("#55280C", "Cioccolato"),
    color!("#555B10", "Saratoga"),
    color!("#556D56", "Finlandia"),
    color!("#5590D9", "Havelock Blue"),
    color!("#56B4BE", "Fountain Blue"),
    color!("#578363", "Spring Leaves"),
    color!("#583401", "Saddle Brown"),
    color!("#585562", "Scarpa Flow"),
    color!("#587156", "Cactus"),
    color!("#589AAF", "Hippie Blue"),
    color!("#591D35", "Wine Berry"),
    color!("#592804", "Brown Bramble"),
    color!("#593737", "Congo Brown"),
    color!("#594433", "Millbrook"),
    color!("#5A6E9C", "Waikawa Gray"),
    color!("#5A87A0", "Horizon"),
    color!("#5B3013", "Jambalaya"),
    color!("#5C0120", "Bordeaux"),
    color!("#5C0536", "Mulberry Wood"),
    color!("#5C2E01", "Carnaby Tan"),
    color!("#5C5D75", "Comet"),
    color!("#5D1E0F", "Redwood"),
    color!("#5D4C51", "Don Juan"),
    color!("#5D5C58", "Chicago"),
    color!("#5D5E37", "Verdigris"),
    color!("#5D7747", "Dingley"),
    color!("#5DA19F", "Breaker Bay"),
    color!("#5E483E", "Kabul"),
    color!("#5E5D3B", "Hemlock"),
    color!("#5F3D26", "Irish Coffee"),
    color!("#5F5F6E", "Mid Gray"),
    color!("#5F6672", "Shuttle Gray"),
    color!("#5FA777", "Aqua Forest"),
    color!("#5FB3AC", "Tradewind"),
    color!("#604913", "Horses Neck"),
    color!("#605B73", "Smoky"),
    color!("#606E68", "Corduroy"),
    color!("#6093D1", "Danube"),
    color!("#612718", "Espresso"),
    color!("#614051", "Eggplant"),
    color!("#615D30", "Costa Del Sol"),
    color!("#61845F", "Glade Green"),
    color!("#622F30", "Buccaneer"),
    color!("#623F2D", "Quincy"),
    color!("#624E9A", "Butterfly Bush"),
    color!("#625119", "West Coast"),
    color!("#626649", "Finch"),
    color!("#639A8F", "Patina"),
    color!("#63B76C", "Fern"),
    color!("#6456B7", "Blue Violet"),
    color!("#646077", "Dolphin"),
    color!("#646463", "Storm Dust"),
    color!("#646A54", "Siam"),
    color!("#646E75", "Nevada"),
    color!("#6495ED", "Cornflower Blue"),
    color!("#64CCDB", "Viking"),
    color!("#65000B", "Rosewood"),
    color!("#651A14", "Cherrywood"),
    color!("#652DC1", "Purple Heart"),
    color!("#657220", "Fern Frond"),
    color!("#65745D", "Willow Grove"),
    color!("#65869F", "Hoki"),
    color!("#660045", "Pompadour"),
    color!("#660099", "Purple"),
    color!("#66023C", "Tyrian Purple"),
    color!("#661010", "Dark Tan"),
    color!("#66B58F", "Silver Tree"),
    color!("#66FF00", "Bright Green"),
    color!("#66FF66", "Screamin' Green"),
    color!("#67032D", "Black Rose"),
    color!("#675FA6", "Scampi"),
    color!("#676662", "Ironside Gray"),
    color!("#678975", "Viridian Green"),
    color!("#67A712", "Christi"),
    color!("#683600", "Nutmeg Wood Finish"),
    color!("#685558", "Zambezi"),
    color!("#685E6E", "Salt Box"),
    color!("#692545", "Tawny Port"),
    color!("#692D54", "Finn"),
    color!("#695F62", "Scorpion"),
    color!("#697E9A", "Lynch"),
    color!("#6A442E", "Spice"),
    color!("#6A5D1B", "Himalaya"),
    color!("#6A6051", "Soya Bean"),
    color!("#6B2A14", "Hairy Heath"),
    color!("#6B3FA0", "Royal Purple"),
    color!("#6B4E31", "Shingle Fawn"),
    color!("#6B5755", "Dorado"),
    color!("#6B8BA2", "Bermuda Gray"),
    color!("#6B8E23", "Olive Drab"),
    color!("#6C3082", "Eminence"),
    color!("#6CDAE7", "Turquoise Blue"),
    color!("#6D0101", "Lonestar"),
    color!("#6D5E54", "Pine Cone"),
    color!("#6D6C6C", "Dove Gray"),
    color!("#6D9292", "Juniper"),
    color!("#6D92A1", "Gothic"),
    color!("#6E0902", "Red Oxide"),
    color!("#6E1D14", "Moccaccino"),
    color!("#6E4826", "Pickled Bean"),
    color!("#6E4B26", "Dallas"),
    color!("#6E6D57", "Kokoda"),
    color!("#6E7783", "Pale Sky"),
    color!("#6F440C", "Cafe Royale"),
    color!("#6F6A61", "Flint"),
    color!("#6F8E63", "Highland"),
    color!("#6F9D02", "Limeade"),
    color!("#6FD0C5", "Downy"),
    color!("#701C1C", "Persian Plum"),
    color!("#704214", "Sepia"),
    color!("#704A07", "Antique Bronze"),
    color!("#704F50", "Ferra"),
    color!("#706555", "Coffee"),
    color!("#708090", "Slate Gray"),
    color!("#711A00", "Cedar Wood Finish"),
    color!("#71291D", "Metallic Copper"),
    color!("#714693", "Affair"),
    color!("#714AB2", "Studio"),
    color!("#715D47", "Tobacco Brown"),
    color!("#716338", "Yellow Metal"),
    color!("#716B56", "Peat"),
    color!("#716E10", "Olivetone"),
    color!("#717486", "Storm Gray"),
    color!("#718080", "Sirocco"),
    color!("#71D9E2", "Aquamarine Blue"),
    color!("#72010F", "Venetian Red"),
    color!("#724A2F", "Old Copper"),
    color!("#726D4E", "Go Ben"),
    color!("#727B89", "Raven"),
    color!("#731E8F", "Seance"),
    color!("#734A12", "Raw Umber"),
    color!("#736C9F", "Kimberly"),
    color!("#736D58", "Crocodile"),
    color!("#737829", "Crete"),
    color!("#738678", "Xanadu"),
    color!("#74640D", "Spicy Mustard"),
    color!("#747D63", "Limed Ash"),
    color!("#747D83", "Rolling Stone"),
    color!("#748881", "Blue Smoke"),
    color!("#749378", "Laurel"),
    color!("#74C365", "Mantis"),
    color!("#755A57", "Russett"),
    color!("#7563A8", "Deluge"),
    color!("#76395D", "Cosmic"),
    color!("#7666C6", "Blue Marguerite"),
    color!("#76BD17", "Lima"),
    color!("#76D7EA", "Sky Blue"),
    color!("#770F05", "Dark Burgundy"),
    color!("#771F1F", "Crown of Thorns"),
    color!("#773F1A", "Walnut"),
    color!("#776F61", "Pablo"),
    color!("#778120", "Pacifika"),
    color!("#779E86", "Oxley"),
    color!("#77DD77", "Pastel Green"),
    color!("#780109", "Japanese Maple"),
    color!("#782D19", "Mocha"),
    color!("#782F16", "Peanut"),
    color!("#78866B", "Camouflage Green"),
    color!("#788A25", "Wasabi"),
    color!("#788BBA", "Ship Cove"),
    color!("#78A39C", "Sea Nymph"),
    color!("#795D4C", "Roman Coffee"),
    color!("#796878", "Old Lavender"),
    color!("#796989", "Rum"),
    color!("#796A78", "Fedora"),
    color!("#796D62", "Sandstone"),
    color!("#79DEEC", "Spray"),
    color!("#7A013A", "Siren"),
    color!("#7A58C1", "Fuchsia Blue"),
    color!("#7A7A7A", "Boulder"),
    color!("#7A89B8", "Wild Blue Yonder"),
    color!("#7AC488", "De York"),
    color!("#7B3801", "Red Beech"),
    color!("#7B3F00", "Cinnamon"),
    color!("#7B6608", "Yukon Gold"),
    color!("#7B7874", "Tapa"),
    color!("#7B7C94", "Waterloo "),
    color!("#7B8265", "Flax Smoke"),
    color!("#7B9F80", "Amulet"),
    color!("#7BA05B", "Asparagus"),
    color!("#7C1C05", "Kenyan Copper"),
    color!("#7C7631", "Pesto"),
    color!("#7C778A", "Topaz"),
    color!("#7C7B7A", "Concord"),
    color!("#7C7B82", "Jumbo"),
    color!("#7C881A", "Trendy Green"),
    color!("#7CA1A6", "Gumbo"),
    color!("#7CB0A1", "Acapulco"),
    color!("#7CB7BB", "Neptune"),
    color!("#7D2C14", "Pueblo"),
    color!("#7DA98D", "Bay Leaf"),
    color!("#7DC8F7", "Malibu"),
    color!("#7DD8C6", "Bermuda"),
    color!("#7E3A15", "Copper Canyon"),
    color!("#7F1734", "Claret"),
    color!("#7F3A02", "Peru Tan"),
    color!("#7F626D", "Falcon"),
    color!("#7F7589", "Mobster"),
    color!("#7F76D3", "Moody Blue"),
    color!("#7FFF00", "Chartreuse"),
    color!("#7FFFD4", "Aquamarine"),
    color!("#800000", "Maroon"),
    color!("#800B47", "Rose Bud Cherry"),
    color!("#801818", "Falu Red"),
    color!("#80341F", "Red Robin"),
    color!("#803790", "Vivid Violet"),
    color!("#80461B", "Russet"),
    color!("#807E79", "Friar Gray"),
    color!("#808000", "Olive"),
    color!("#808080", "Gray"),
    color!("#80B3AE", "Gulf Stream"),
    color!("#80B3C4", "Glacier"),
    color!("#80CCEA", "Seagull"),
    color!("#81422C", "Nutmeg"),
    color!("#816E71", "Spicy Pink"),
    color!("#817377", "Empress"),
    color!("#819885", "Spanish Green"),
    color!("#826F65", "Sand Dune"),
    color!("#828685", "Gunsmoke"),
    color!("#828F72", "Battleship Gray"),
    color!("#831923", "Merlot"),
    color!("#837050", "Shadow"),
    color!("#83AA5D", "Chelsea Cucumber"),
    color!("#83D0C6", "Monte Carlo"),
    color!("#843179", "Plum"),
    color!("#84A0A0", "Granny Smith"),
    color!("#8581D9", "Chetwode Blue"),
    color!("#858470", "Bandicoot"),
    color!("#859FAF", "Bali Hai"),
    color!("#85C4CC", "Half Baked"),
    color!("#860111", "Red Devil"),
    color!("#863C3C", "Lotus"),
    color!("#86483C", "Ironstone"),
    color!("#864D1E", "Bull Shot"),
    color!("#86560A", "Rusty Nail"),
    color!("#868974", "Bitter"),
    color!("#86949F", "Regent Gray"),
    color!("#871550", "Disco"),
    color!("#87756E", "Americano"),
    color!("#877C7B", "Hurricane"),
    color!("#878D91", "Oslo Gray"),
    color!("#87AB39", "Sushi"),
    color!("#885342", "Spicy Mix"),
    color!("#886221", "Kumera"),
    color!("#888387", "Suva Gray"),
    color!("#888D65", "Avocado"),
    color!("#893456", "Camelot"),
    color!("#893843", "Solid Pink"),
    color!("#894367", "Cannon Pink"),
    color!("#897D6D", "Makara"),
    color!("#8A3324", "Burnt Umber"),
    color!("#8A73D6", "True V"),
    color!("#8A8360", "Clay Creek"),
    color!("#8A8389", "Monsoon"),
    color!("#8A8F8A", "Stack"),
    color!("#8AB9F1", "Jordy Blue"),
    color!("#8B00FF", "Electric Violet"),
    color!("#8B0723", "Monarch"),
    color!("#8B6B0B", "Corn Harvest"),
    color!("#8B8470", "Olive Haze"),
    color!("#8B847E", "Schooner"),
    color!("#8B8680", "Natural Gray"),
    color!("#8B9C90", "Mantle"),
    color!("#8B9FEE", "Portage"),
    color!("#8BA690", "Envy"),
    color!("#8BA9A5", "Cascade"),
    color!("#8BE6D8", "Riptide"),
    color!("#8C055E", "Cardinal Pink"),
    color!("#8C472F", "Mule Fawn"),
    color!("#8C5738", "Potters Clay"),
    color!("#8C6495", "Trendy Pink"),
    color!("#8D0226", "Paprika"),
    color!("#8D3D38", "Sanguine Brown"),
    color!("#8D3F3F", "Tosca"),
    color!("#8D7662", "Cement"),
    color!("#8D8974", "Granite Green"),
    color!("#8D90A1", "Manatee"),
    color!("#8DA8CC", "Polo Blue"),
    color!("#8E0000", "Red Berry"),
    color!("#8E4D1E", "Rope"),
    color!("#8E6F70", "Opium"),
    color!("#8E775E", "Domino"),
    color!("#8E8190", "Mamba"),
    color!("#8EABC1", "Nepal"),
    color!("#8F021C", "Pohutukawa"),
    color!("#8F3E33", "El Salva"),
    color!("#8F4B0E", "Korma"),
    color!("#8F8176", "Squirrel"),
    color!("#8FD6B4", "Vista Blue"),
    color!("#900020", "Burgundy"),
    color!("#901E1E", "Old Brick"),
    color!("#907874", "Hemp"),
    color!("#907B71", "Almond Frost"),
    color!("#908D39", "Sycamore"),
    color!("#92000A", "Sangria"),
    color!("#924321", "Cumin"),
    color!("#926F5B", "Beaver"),
    color!("#928573", "Stonewall"),
    color!("#928590", "Venus"),
    color!("#9370DB", "Medium Purple"),
    color!("#93CCEA", "Cornflower"),
    color!("#93DFB8", "Algae Green"),
    color!("#944747", "Copper Rust"),
    color!("#948771", "Arrowtown"),
    color!("#950015", "Scarlett"),
    color!("#956387", "Strikemaster"),
    color!("#959396", "Mountain Mist"),
    color!("#960018", "Carmine"),
    color!("#964B00", "Brown"),
    color!("#967059", "Leather"),
    color!("#9678B6", "Purple Mountain's Majesty"),
    color!("#967BB6", "Lavender Purple"),
    color!("#96A8A1", "Pewter"),
    color!("#96BBAB", "Summer Green"),
    color!("#97605D", "Au Chico"),
    color!("#9771B5", "Wisteria"),
    color!("#97CD2D", "Atlantis"),
    color!("#983D61", "Vin Rouge"),
    color!("#9874D3", "Lilac Bush"),
    color!("#98777B", "Bazaar"),
    color!("#98811B", "Hacienda"),
    color!("#988D77", "Pale Oyster"),
    color!("#98FF98", "Mint Green"),
    color!("#990066", "Fresh Eggplant"),
    color!("#991199", "Violet Eggplant"),
    color!("#991613", "Tamarillo"),
    color!("#991B07", "Totem Pole"),
    color!("#996666", "Copper Rose"),
    color!("#9966CC", "Amethyst"),
    color!("#997A8D", "Mountbatten Pink"),
    color!("#9999CC", "Blue Bell"),
    color!("#9A3820", "Prairie Sand"),
    color!("#9A6E61", "Toast"),
    color!("#9A9577", "Gurkha"),
    color!("#9AB973", "Olivine"),
    color!("#9AC2B8", "Shadow Green"),
    color!("#9B4703", "Oregon"),
    color!("#9B9E8F", "Lemon Grass"),
    color!("#9C3336", "Stiletto"),
    color!("#9D5616", "Hawaiian Tan"),
    color!("#9DACB7", "Gull Gray"),
    color!("#9DC209", "Pistachio"),
    color!("#9DE093", "Granny Smith Apple"),
    color!("#9DE5FF", "Anakiwa"),
    color!("#9E5302", "Chelsea Gem"),
    color!("#9E5B40", "Sepia Skin"),
    color!("#9EA587", "Sage"),
    color!("#9EA91F", "Citron"),
    color!("#9EB1CD", "Rock Blue"),
    color!("#9EDEE0", "Morning Glory"),
    color!("#9F381D", "Cognac"),
    color!("#9F821C", "Reef Gold"),
    color!("#9F9F9C", "Star Dust"),
    color!("#9FA0B1", "Santas Gray"),
    color!("#9FD7D3", "Sinbad"),
    color!("#9FDD8C", "Feijoa"),
    color!("#A02712", "Tabasco"),
    color!("#A1750D", "Buttered Rum"),
    color!("#A1ADB5", "Hit Gray"),
    color!("#A1C50A", "Citrus"),
    color!("#A1DAD7", "Aqua Island"),
    color!("#A1E9DE", "Water Leaf"),
    color!("#A2006D", "Flirt"),
    color!("#A23B6C", "Rouge"),
    color!("#A26645", "Cape Palliser"),
    color!("#A2AAB3", "Gray Chateau"),
    color!("#A2AEAB", "Edward"),
    color!("#A3807B", "Pharlap"),
    color!("#A397B4", "Amethyst Smoke"),
    color!("#A3E3ED", "Blizzard Blue"),
    color!("#A4A49D", "Delta"),
    color!("#A4A6D3", "Wistful"),
    color!("#A4AF6E", "Green Smoke"),
    color!("#A50B5E", "Jazzberry Jam"),
    color!("#A59B91", "Zorba"),
    color!("#A5CB0C", "Bahia"),
    color!("#A62F20", "Roof Terracotta"),
    color!("#A65529", "Paarl"),
    color!("#A68B5B", "Barley Corn"),
    color!("#A69279", "Donkey Brown"),
    color!("#A6A29A", "Dawn"),
    color!("#A72525", "Mexican Red"),
    color!("#A7882C", "Luxor Gold"),
    color!("#A85307", "Rich Gold"),
    color!("#A86515", "Reno Sand"),
    color!("#A86B6B", "Coral Tree"),
    color!("#A8989B", "Dusty Gray"),
    color!("#A899E6", "Dull Lavender"),
    color!("#A8A589", "Tallow"),
    color!("#A8AE9C", "Bud"),
    color!("#A8AF8E", "Locust"),
    color!("#A8BD9F", "Norway"),
    color!("#A8E3BD", "Chinook"),
    color!("#A9A491", "Gray Olive"),
    color!("#A9ACB6", "Aluminium"),
    color!("#A9B2C3", "Cadet Blue"),
    color!("#A9B497", "Schist"),
    color!("#A9BDBF", "Tower Gray"),
    color!("#A9BEF2", "Perano"),
    color!("#A9C6C2", "Opal"),
    color!("#AA375A", "Night Shadz"),
    color!("#AA4203", "Fire"),
    color!("#AA8B5B", "Muesli"),
    color!("#AA8D6F", "Sandal"),
    color!("#AAA5A9", "Shady Lady"),
    color!("#AAA9CD", "Logan"),
    color!("#AAABB7", "Spun Pearl"),
    color!("#AAD6E6", "Regent St Blue"),
    color!("#AAF0D1", "Magic Mint"),
    color!("#AB0563", "Lipstick"),
    color!("#AB3472", "Royal Heath"),
    color!("#AB917A", "Sandrift"),
    color!("#ABA0D9", "Cold Purple"),
    color!("#ABA196", "Bronco"),
    color!("#AC8A56", "Limed Oak"),
    color!("#AC91CE", "East Side"),
    color!("#AC9E22", "Lemon Ginger"),
    color!("#ACA494", "Napa"),
    color!("#ACA586", "Hillary"),
    color!("#ACA59F", "Cloudy"),
    color!("#ACACAC", "Silver Chalice"),
    color!("#ACB78E", "Swamp Green"),
    color!("#ACCBB1", "Spring Rain"),
    color!("#ACDD4D", "Conifer"),
    color!("#ACE1AF", "Celadon"),
    color!("#AD781B", "Mandalay"),
    color!("#ADBED1", "Casper"),
    color!("#ADDFAD", "Moss Green"),
    color!("#ADE6C4", "Padua"),
    color!("#ADFF2F", "Green Yellow"),
    color!("#AE4560", "Hippie Pink"),
    color!("#AE6020", "Desert"),
    color!("#AE809E", "Bouquet"),
    color!("#AF4035", "Medium Carmine"),
    color!("#AF4D43", "Apple Blossom"),
    color!("#AF593E", "Brown Rust"),
    color!("#AF8751", "Driftwood"),
    color!("#AF8F2C", "Alpine"),
    color!("#AF9F1C", "Lucky"),
    color!("#AFA09E", "Martini"),
    color!("#AFB1B8", "Bombay"),
    color!("#AFBDD9", "Pigeon Post"),
    color!("#B04C6A", "Cadillac"),
    color!("#B05D54", "Matrix"),
    color!("#B05E81", "Tapestry"),
    color!("#B06608", "Mai Tai"),
    color!("#B09A95", "Del Rio"),
    color!("#B0E0E6", "Powder Blue"),
    color!("#B0E313", "Inch Worm"),
    color!("#B10000", "Bright Red"),
    color!("#B14A0B", "Vesuvius"),
    color!("#B1610B", "Pumpkin Skin"),
    color!("#B16D52", "Santa Fe"),
    color!("#B19461", "Teak"),
    color!("#B1E2C1", "Fringy Flower"),
    color!("#B1F4E7", "Ice Cold"),
    color!("#B20931", "Shiraz"),
    color!("#B2A1EA", "Biloba Flower"),
    color!("#B32D29", "Tall Poppy"),
    color!("#B35213", "Fiery Orange"),
    color!("#B38007", "Hot Toddy"),
    color!("#B3AF95", "Taupe Gray"),
    color!("#B3C110", "La Rioja"),
    color!("#B43332", "Well Read"),
    color!("#B44668", "Blush"),
    color!("#B4CFD3", "Jungle Mist"),
    color!("#B57281", "Turkish Rose"),
    color!("#B57EDC", "Lavender"),
    color!("#B5A27F", "Mongoose"),
    color!("#B5B35C", "Olive Green"),
    color!("#B5D2CE", "Jet Stream"),
    color!("#B5ECDF", "Cruise"),
    color!("#B6316C", "Hibiscus"),
    color!("#B69D98", "Thatch"),
    color!("#B6B095", "Heathered Gray"),
    color!("#B6BAA4", "Eagle"),
    color!("#B6D1EA", "Spindle"),
    color!("#B6D3BF", "Gum Leaf"),
    color!("#B7410E", "Rust"),
    color!("#B78E5C", "Muddy Waters"),
    color!("#B7A214", "Sahara"),
    color!("#B7A458", "Husk"),
    color!("#B7B1B1", "Nobel"),
    color!("#B7C3D0", "Heather"),
    color!("#B7F0BE", "Madang"),
    color!("#B81104", "Milano Red"),
    color!("#B87333", "Copper"),
    color!("#B8B56A", "Gimblet"),
    color!("#B8C1B1", "Green Spring"),
    color!("#B8C25D", "Celery"),
    color!("#B8E0F9", "Sail"),
    color!("#B94E48", "Chestnut"),
    color!("#B95140", "Crail"),
    color!("#B98D28", "Marigold"),
    color!("#B9C46A", "Wild Willow"),
    color!("#B9C8AC", "Rainee"),
    color!("#BA0101", "Guardsman Red"),
    color!("#BA450C", "Rock Spray"),
    color!("#BA6F1E", "Bourbon"),
    color!("#BA7F03", "Pirate Gold"),
    color!("#BAB1A2", "Nomad"),
    color!("#BAC7C9", "Submarine"),
    color!("#BAEEF9", "Charlotte"),
    color!("#BB3385", "Medium Red Violet"),
    color!("#BB8983", "Brandy Rose"),
    color!("#BBD009", "Rio Grande"),
    color!("#BBD7C1", "Surf"),
    color!("#BCC9C2", "Powder Ash"),
    color!("#BD5E2E", "Tuscany"),
    color!("#BD978E", "Quicksand"),
    color!("#BDB1A8", "Silk"),
    color!("#BDB2A1", "Malta"),
    color!("#BDB3C7", "Chatelle"),
    color!("#BDBBD7", "Lavender Gray"),
    color!("#BDBDC6", "French Gray"),
    color!("#BDC8B3", "Clay Ash"),
    color!("#BDC9CE", "Loblolly"),
    color!("#BDEDFD", "French Pass"),
    color!("#BEA6C3", "London Hue"),
    color!("#BEB5B7", "Pink Swan"),
    color!("#BEDE0D", "Fuego"),
    color!("#BF5500", "Rose of Sharon"),
    color!("#BFB8B0", "Tide"),
    color!("#BFBED8", "Blue Haze"),
    color!("#BFC1C2", "Silver Sand"),
    color!("#BFC921", "Key Lime Pie"),
    color!("#BFDBE2", "Ziggurat"),
    color!("#BFFF00", "Lime"),
    color!("#C02B18", "Thunderbird"),
    color!("#C04737", "Mojo"),
    color!("#C08081", "Old Rose"),
    color!("#C0C0C0", "Silver"),
    color!("#C0D3B9", "Pale Leaf"),
    color!("#C0D8B6", "Pixie Green"),
    color!("#C1440E", "Tia Maria"),
    color!("#C154C1", "Fuchsia Pink"),
    color!("#C1A004", "Buddha Gold"),
    color!("#C1B7A4", "Bison Hide"),
    color!("#C1BAB0", "Tea"),
    color!("#C1BECD", "Gray Suit"),
    color!("#C1D7B0", "Sprout"),
    color!("#C1F07C", "Sulu"),
    color!("#C26B03", "Indochine"),
    color!("#C2955D", "Twine"),
    color!("#C2BDB6", "Cotton Seed"),
    color!("#C2CAC4", "Pumice"),
    color!("#C2E8E5", "Jagged Ice"),
    color!("#C32148", "Maroon Flush"),
    color!("#C3B091", "Indian Khaki"),
    color!("#C3BFC1", "Pale Slate"),
    color!("#C3C3BD", "Gray Nickel"),
    color!("#C3CDE6", "Periwinkle Gray"),
    color!("#C3D1D1", "Tiara"),
    color!("#C3DDF9", "Tropical Blue"),
    color!("#C41E3A", "Cardinal"),
    color!("#C45655", "Fuzzy Wuzzy Brown"),
    color!("#C45719", "Orange Roughy"),
    color!("#C4C4BC", "Mist Gray"),
    color!("#C4D0B0", "Coriander"),
    color!("#C4F4EB", "Mint Tulip"),
    color!("#C54B8C", "Mulberry"),
    color!("#C59922", "Nugget"),
    color!("#C5994B", "Tussock"),
    color!("#C5DBCA", "Sea Mist"),
    color!("#C5E17A", "Yellow Green"),
    color!("#C62D42", "Brick Red"),
    color!("#C6726B", "Contessa"),
    color!("#C69191", "Oriental Pink"),
    color!("#C6A84B", "Roti"),
    color!("#C6C3B5", "Ash"),
    color!("#C6C8BD", "Kangaroo"),
    color!("#C6E610", "Las Palmas"),
    color!("#C7031E", "Monza"),
    color!("#C71585", "Red Violet"),
    color!("#C7BCA2", "Coral Reef"),
    color!("#C7C1FF", "Melrose"),
    color!("#C7C4BF", "Cloud"),
    color!("#C7C9D5", "Ghost"),
    color!("#C7CD90", "Pine Glade"),
    color!("#C7DDE5", "Botticelli"),
    color!("#C88A65", "Antique Brass"),
    color!("#C8A2C8", "Lilac"),
    color!("#C8A528", "Hokey Pokey"),
    color!("#C8AABF", "Lily"),
    color!("#C8B568", "Laser"),
    color!("#C8E3D7", "Edgewater"),
    color!("#C96323", "Piper"),
    color!("#C99415", "Pizza"),
    color!("#C9A0DC", "Light Wisteria"),
    color!("#C9B29B", "Rodeo Dust"),
    color!("#C9B35B", "Sundance"),
    color!("#C9B93B", "Earls Green"),
    color!("#C9C0BB", "Silver Rust"),
    color!("#C9D9D2", "Conch"),
    color!("#C9FFA2", "Reef"),
    color!("#C9FFE5", "Aero Blue"),
    color!("#CA3435", "Flush Mahogany"),
    color!("#CABB48", "Turmeric"),
    color!("#CADCD4", "Paris White"),
    color!("#CAE00D", "Bitter Lemon"),
    color!("#CAE6DA", "Skeptic"),
    color!("#CB8FA9", "Viola"),
    color!("#CBCAB6", "Foggy Gray"),
    color!("#CBD3B0", "Green Mist"),
    color!("#CBDBD6", "Nebula"),
    color!("#CC3333", "Persian Red"),
    color!("#CC5500", "Burnt Orange"),
    color!("#CC7722", "Ochre"),
    color!("#CC8899", "Puce"),
    color!("#CCCAA8", "Thistle Green"),
    color!("#CCCCFF", "Periwinkle"),
    color!("#CCFF00", "Electric Lime"),
    color!("#CD5700", "Tenn"),
    color!("#CD5C5C", "Chestnut Rose"),
    color!("#CD8429", "Brandy Punch"),
    color!("#CDF4FF", "Onahau"),
    color!("#CEB98F", "Sorrell Brown"),
    color!("#CEBABA", "Cold Turkey"),
    color!("#CEC291", "Yuma"),
    color!("#CEC7A7", "Chino"),
    color!("#CFA39D", "Eunry"),
    color!("#CFB53B", "Old Gold"),
    color!("#CFDCCF", "Tasman"),
    color!("#CFE5D2", "Surf Crest"),
    color!("#CFF9F3", "Humming Bird"),
    color!("#CFFAF4", "Scandal"),
    color!("#D05F04", "Red Stage"),
    color!("#D06DA1", "Hopbush"),
    color!("#D07D12", "Meteor"),
    color!("#D0BEF8", "Perfume"),
    color!("#D0C0E5", "Prelude"),
    color!("#D0F0C0", "Tea Green"),
    color!("#D18F1B", "Geebung"),
    color!("#D1BEA8", "Vanilla"),
    color!("#D1C6B4", "Soft Amber"),
    color!("#D1D2CA", "Celeste"),
    color!("#D1D2DD", "Mischka"),
    color!("#D1E231", "Pear"),
    color!("#D2691E", "Hot Cinnamon"),
    color!("#D27D46", "Raw Sienna"),
    color!("#D29EAA", "Careys Pink"),
    color!("#D2B48C", "Tan"),
    color!("#D2DA97", "Deco"),
    color!("#D2F6DE", "Blue Romance"),
    color!("#D2F8B0", "Gossip"),
    color!("#D3CBBA", "Sisal"),
    color!("#D3CDC5", "Swirl"),
    color!("#D47494", "Charm"),
    color!("#D4B6AF", "Clam Shell"),
    color!("#D4BF8D", "Straw"),
    color!("#D4C4A8", "Akaroa"),
    color!("#D4CD16", "Bird Flower"),
    color!("#D4D7D9", "Iron"),
    color!("#D4DFE2", "Geyser"),
    color!("#D4E2FC", "Hawkes Blue"),
    color!("#D54600", "Grenadier"),
    color!("#D591A4", "Can Can"),
    color!("#D59A6F", "Whiskey"),
    color!("#D5D195", "Winter Hazel"),
    color!("#D5F6E3", "Granny Apple"),
    color!("#D69188", "My Pink"),
    color!("#D6C562", "Tacha"),
    color!("#D6CEF6", "Moon Raker"),
    color!("#D6D6D1", "Quill Gray"),
    color!("#D6FFDB", "Snowy Mint"),
    color!("#D7837F", "New York Pink"),
    color!("#D7C498", "Pavlova"),
    color!("#D7D0FF", "Fog"),
    color!("#D84437", "Valencia"),
    color!("#D87C63", "Japonica"),
    color!("#D8BFD8", "Thistle"),
    color!("#D8C2D5", "Maverick"),
    color!("#D8FCFA", "Foam"),
    color!("#D94972", "Cabaret"),
    color!("#D99376", "Burning Sand"),
    color!("#D9B99B", "Cameo"),
    color!("#D9D6CF", "Timberwolf"),
    color!("#D9DCC1", "Tana"),
    color!("#D9E4F5", "Link Water"),
    color!("#D9F7FF", "Mabel"),
    color!("#DA3287", "Cerise"),
    color!("#DA5B38", "Flame Pea"),
    color!("#DA6304", "Bamboo"),
    color!("#DA6A41", "Red Damask"),
    color!("#DA70D6", "Orchid"),
    color!("#DA8A67", "Copperfield"),
    color!("#DAA520", "Golden Grass"),
    color!("#DAECD6", "Zanah"),
    color!("#DAF4F0", "Iceberg"),
    color!("#DAFAFF", "Oyster Bay"),
    color!("#DB5079", "Cranberry"),
    color!("#DB9690", "Petite Orchid"),
    color!("#DB995E", "Di Serria"),
    color!("#DBDBDB", "Alto"),
    color!("#DBFFF8", "Frosted Mint"),
    color!("#DC143C", "Crimson"),
    color!("#DC4333", "Punch"),
    color!("#DCB20C", "Galliano"),
    color!("#DCB4BC", "Blossom"),
    color!("#DCD747", "Wattle"),
    color!("#DCD9D2", "Westar"),
    color!("#DCDDCC", "Moon Mist"),
    color!("#DCEDB4", "Caper"),
    color!("#DCF0EA", "Swans Down"),
    color!("#DDD6D5", "Swiss Coffee"),
    color!("#DDF9F1", "White Ice"),
    color!("#DE3163", "Cerise Red"),
    color!("#DE6360", "Roman"),
    color!("#DEA681", "Tumbleweed"),
    color!("#DEBA13", "Gold Tips"),
    color!("#DEC196", "Brandy"),
    color!("#DECBC6", "Wafer"),
    color!("#DED4A4", "Sapling"),
    color!("#DED717", "Barberry"),
    color!("#DEE5C0", "Beryl Green"),
    color!("#DEF5FF", "Pattens Blue"),
    color!("#DF73FF", "Heliotrope"),
    color!("#DFBE6F", "Apache"),
    color!("#DFCD6F", "Chenin"),
    color!("#DFCFDB", "Lola"),
    color!("#DFECDA", "Willow Brook"),
    color!("#DFFF00", "Chartreuse Yellow"),
    color!("#E0B0FF", "Mauve"),
    color!("#E0B646", "Anzac"),
    color!("#E0B974", "Harvest Gold"),
    color!("#E0C095", "Calico"),
    color!("#E0FFFF", "Baby Blue"),
    color!("#E16865", "Sunglo"),
    color!("#E1BC64", "Equator"),
    color!("#E1C0C8", "Pink Flare"),
    color!("#E1E6D6", "Periglacial Blue"),
    color!("#E1EAD4", "Kidnapper"),
    color!("#E1F6E8", "Tara"),
    color!("#E25465", "Mandy"),
    color!("#E2725B", "Terracotta"),
    color!("#E28913", "Golden Bell"),
    color!("#E292C0", "Shocking"),
    color!("#E29418", "Dixie"),
    color!("#E29CD2", "Light Orchid"),
    color!("#E2D8ED", "Snuff"),
    color!("#E2EBED", "Mystic"),
    color!("#E2F3EC", "Apple Green"),
    color!("#E30B5C", "Razzmatazz"),
    color!("#E32636", "Alizarin Crimson"),
    color!("#E34234", "Cinnabar"),
    color!("#E3BEBE", "Cavern Pink"),
    color!("#E3F5E1", "Peppermint"),
    color!("#E3F988", "Mindaro"),
    color!("#E47698", "Deep Blush"),
    color!("#E49B0F", "Gamboge"),
    color!("#E4C2D5", "Melanie"),
    color!("#E4CFDE", "Twilight"),
    color!("#E4D1C0", "Bone"),
    color!("#E4D422", "Sunflower"),
    color!("#E4D5B7", "Grain Brown"),
    color!("#E4D69B", "Zombie"),
    color!("#E4F6E7", "Frostee"),
    color!("#E4FFD1", "Snow Flurry"),
    color!("#E52B50", "Amaranth"),
    color!("#E5841B", "Zest"),
    color!("#E5CCC9", "Dust Storm"),
    color!("#E5D7BD", "Stark White"),
    color!("#E5D8AF", "Hampton"),
    color!("#E5E0E1", "Bon Jour"),
    color!("#E5E5E5", "Mercury"),
    color!("#E5F9F6", "Polar"),
    color!("#E64E03", "Trinidad"),
    color!("#E6BE8A", "Gold Sand"),
    color!("#E6BEA5", "Cashmere"),
    color!("#E6D7B9", "Double Spanish White"),
    color!("#E6E4D4", "Satin Linen"),
    color!("#E6F2EA", "Harp"),
    color!("#E6F8F3", "Off Green"),
    color!("#E6FFE9", "Hint of Green"),
    color!("#E6FFFF", "Tranquil"),
    color!("#E77200", "Mango Tango"),
    color!("#E7730A", "Christine"),
    color!("#E79F8C", "Tonys Pink"),
    color!("#E79FC4", "Kobi"),
    color!("#E7BCB4", "Rose Fog"),
    color!("#E7BF05", "Corn"),
    color!("#E7CD8C", "Putty"),
    color!("#E7ECE6", "Gray Nurse"),
    color!("#E7F8FF", "Lily White"),
    color!("#E7FEFF", "Bubbles"),
    color!("#E89928", "Fire Bush"),
    color!("#E8B9B3", "Shilo"),
    color!("#E8E0D5", "Pearl Bush"),
    color!("#E8EBE0", "Green White"),
    color!("#E8F1D4", "Chrome White"),
    color!("#E8F2EB", "Gin"),
    color!("#E8F5F2", "Aqua Squeeze"),
    color!("#E96E00", "Clementine"),
    color!("#E97451", "Burnt Sienna"),
    color!("#E97C07", "Tahiti Gold"),
    color!("#E9CECD", "Oyster Pink"),
    color!("#E9D75A", "Confetti"),
    color!("#E9E3E3", "Ebb"),
    color!("#E9F8ED", "Ottoman"),
    color!("#E9FFFD", "Clear Day"),
    color!("#EA88A8", "Carissma"),
    color!("#EAAE69", "Porsche"),
    color!("#EAB33B", "Tulip Tree"),
    color!("#EAC674", "Rob Roy"),
    color!("#EADAB8", "Raffia"),
    color!("#EAE8D4", "White Rock"),
    color!("#EAF6EE", "Panache"),
    color!("#EAF6FF", "Solitude"),
    color!("#EAF9F5", "Aqua Spring"),
    color!("#EAFFFE", "Dew"),
    color!("#EB9373", "Apricot"),
    color!("#EBC2AF", "Zinnwaldite"),
    color!("#ECA927", "Fuel Yellow"),
    color!("#ECC54E", "Ronchi"),
    color!("#ECC7EE", "French Lilac"),
    color!("#ECCDB9", "Just Right"),
    color!("#ECE090", "Wild Rice"),
    color!("#ECEBBD", "Fall Green"),
    color!("#ECEBCE", "Aths Special"),
    color!("#ECF245", "Starship"),
    color!("#ED0A3F", "Red Ribbon"),
    color!("#ED7A1C", "Tango"),
    color!("#ED9121", "Carrot Orange"),
    color!("#ED989E", "Sea Pink"),
    color!("#EDB381", "Tacao"),
    color!("#EDC9AF", "Desert Sand"),
    color!("#EDCDAB", "Pancho"),
    color!("#EDDCB1", "Chamois"),
    color!("#EDEA99", "Primrose"),
    color!("#EDF5DD", "Frost"),
    color!("#EDF5F5", "Aqua Haze"),
    color!("#EDF6FF", "Zumthor"),
    color!("#EDF9F1", "Narvik"),
    color!("#EDFC84", "Honeysuckle"),
    color!("#EE82EE", "Lavender Magenta"),
    color!("#EEC1BE", "Beauty Bush"),
    color!("#EED794", "Chalky"),
    color!("#EED9C4", "Almond"),
    color!("#EEDC82", "Flax"),
    color!("#EEDEDA", "Bizarre"),
    color!("#EEE3AD", "Double Colonial White"),
    color!("#EEEEE8", "Cararra"),
    color!("#EEEF78", "Manz"),
    color!("#EEF0C8", "Tahuna Sands"),
    color!("#EEF0F3", "Athens Gray"),
    color!("#EEF3C3", "Tusk"),
    color!("#EEF4DE", "Loafer"),
    color!("#EEF6F7", "Catskill White"),
    color!("#EEFDFF", "Twilight Blue"),
    color!("#EEFF9A", "Jonquil"),
    color!("#EEFFE2", "Rice Flower"),
    color!("#EF863F", "Jaffa"),
    color!("#EFEFEF", "Gallery"),
    color!("#EFF2F3", "Porcelain"),
    color!("#F091A9", "Mauvelous"),
    color!("#F0D52D", "Golden Dream"),
    color!("#F0DB7D", "Golden Sand"),
    color!("#F0DC82", "Buff"),
    color!("#F0E2EC", "Prim"),
    color!("#F0E68C", "Khaki"),
    color!("#F0EEFD", "Selago"),
    color!("#F0EEFF", "Titan White"),
    color!("#F0F8FF", "Alice Blue"),
    color!("#F0FCEA", "Feta"),
    color!("#F18200", "Gold Drop"),
    color!("#F19BAB", "Wewak"),
    color!("#F1E788", "Sahara Sand"),
    color!("#F1E9D2", "Parchment"),
    color!("#F1E9FF", "Blue Chalk"),
    color!("#F1EEC1", "Mint Julep"),
    color!("#F1F1F1", "Seashell"),
    color!("#F1F7F2", "Saltpan"),
    color!("#F1FFAD", "Tidal"),
    color!("#F1FFC8", "Chiffon"),
    color!("#F2552A", "Flamingo"),
    color!("#F28500", "Tangerine"),
    color!("#F2C3B2", "Mandys Pink"),
    color!("#F2F2F2", "Concrete"),
    color!("#F2FAFA", "Black Squeeze"),
    color!("#F34723", "Pomegranate"),
    color!("#F3AD16", "Buttercup"),
    color!("#F3D69D", "New Orleans"),
    color!("#F3D9DF", "Vanilla Ice"),
    color!("#F3E7BB", "Sidecar"),
    color!("#F3E9E5", "Dawn Pink"),
    color!("#F3EDCF", "Wheatfield"),
    color!("#F3FB62", "Canary"),
    color!("#F3FBD4", "Orinoco"),
    color!("#F3FFD8", "Carla"),
    color!("#F400A1", "Hollywood Cerise"),
    color!("#F4A460", "Sandy brown"),
    color!("#F4C430", "Saffron"),
    color!("#F4D81C", "Ripe Lemon"),
    color!("#F4EBD3", "Janna"),
    color!("#F4F2EE", "Pampas"),
    color!("#F4F4F4", "Wild Sand"),
    color!("#F4F8FF", "Zircon"),
    color!("#F57584", "Froly"),
    color!("#F5C85C", "Cream Can"),
    color!("#F5C999", "Manhattan"),
    color!("#F5D5A0", "Maize"),
    color!("#F5DEB3", "Wheat"),
    color!("#F5E7A2", "Sandwisp"),
    color!("#F5E7E2", "Pot Pourri"),
    color!("#F5E9D3", "Albescent White"),
    color!("#F5EDEF", "Soft Peach"),
    color!("#F5F3E5", "Ecru White"),
    color!("#F5F5DC", "Beige"),
    color!("#F5FB3D", "Golden Fizz"),
    color!("#F5FFBE", "Australian Mint"),
    color!("#F64A8A", "French Rose"),
    color!("#F653A6", "Brilliant Rose"),
    color!("#F6A4C9", "Illusion"),
    color!("#F6F0E6", "Merino"),
    color!("#F6F7F7", "Black Haze"),
    color!("#F6FFDC", "Spring Sun"),
    color!("#F7468A", "Violet Red"),
    color!("#F77703", "Chilean Fire"),
    color!("#F77FBE", "Persian Pink"),
    color!("#F7B668", "Rajah"),
    color!("#F7C8DA", "Azalea"),
    color!("#F7DBE6", "We Peep"),
    color!("#F7F2E1", "Quarter Spanish White"),
    color!("#F7F5FA", "Whisper"),
    color!("#F7FAF7", "Snow Drift"),
    color!("#F8B853", "Casablanca"),
    color!("#F8C3DF", "Chantilly"),
    color!("#F8D9E9", "Cherub"),
    color!("#F8DB9D", "Marzipan"),
    color!("#F8DD5C", "Energy Yellow"),
    color!("#F8E4BF", "Givry"),
    color!("#F8F0E8", "White Linen"),
    color!("#F8F4FF", "Magnolia"),
    color!("#F8F6F1", "Spring Wood"),
    color!("#F8F7DC", "Coconut Cream"),
    color!("#F8F7FC", "White Lilac"),
    color!("#F8F8F7", "Desert Storm"),
    color!("#F8F99C", "Texas"),
    color!("#F8FACD", "Corn Field"),
    color!("#F8FDD3", "Mimosa"),
    color!("#F95A61", "Carnation"),
    color!("#F9BF58", "Saffron Mango"),
    color!("#F9E0ED", "Carousel Pink"),
    color!("#F9E4BC", "Dairy Cream"),
    color!("#F9E663", "Portica"),
    color!("#F9EAF3", "Amour"),
    color!("#F9F8E4", "Rum Swizzle"),
    color!("#F9FF8B", "Dolly"),
    color!("#F9FFF6", "Sugar Cane"),
    color!("#FA7814", "Ecstasy"),
    color!("#FA9D5A", "Tan Hide"),
    color!("#FAD3A2", "Corvette"),
    color!("#FADFAD", "Peach Yellow"),
    color!("#FAE600", "Turbo"),
    color!("#FAEAB9", "Astra"),
    color!("#FAECCC", "Champagne"),
    color!("#FAF0E6", "Linen"),
    color!("#FAF3F0", "Fantasy"),
    color!("#FAF7D6", "Citrine White"),
    color!("#FAFAFA", "Alabaster"),
    color!("#FAFDE4", "Hint of Yellow"),
    color!("#FAFFA4", "Milan"),
    color!("#FB607F", "Brink Pink"),
    color!("#FB8989", "Geraldine"),
    color!("#FBA0E3", "Lavender Rose"),
    color!("#FBA129", "Sea Buckthorn"),
    color!("#FBAC13", "Sun"),
    color!("#FBAED2", "Lavender Pink"),
    color!("#FBB2A3", "Rose Bud"),
    color!("#FBBEDA", "Cupid"),
    color!("#FBCCE7", "Classic Rose"),
    color!("#FBCEB1", "Apricot Peach"),
    color!("#FBE7B2", "Banana Mania"),
    color!("#FBE870", "Marigold Yellow"),
    color!("#FBE96C", "Festival"),
    color!("#FBEA8C", "Sweet Corn"),
    color!("#FBEC5D", "Candy Corn"),
    color!("#FBF9F9", "Hint of Red"),
    color!("#FBFFBA", "Shalimar"),
    color!("#FC0FC0", "Shocking Pink"),
    color!("#FC80A5", "Tickle Me Pink"),
    color!("#FC9C1D", "Tree Poppy"),
    color!("#FCC01E", "Lightning Yellow"),
    color!("#FCD667", "Goldenrod"),
    color!("#FCD917", "Candlelight"),
    color!("#FCDA98", "Cherokee"),
    color!("#FCF4D0", "Double Pearl Lusta"),
    color!("#FCF4DC", "Pearl Lusta"),
    color!("#FCF8F7", "Vista White"),
    color!("#FCFBF3", "Bianca"),
    color!("#FCFEDA", "Moon Glow"),
    color!("#FCFFE7", "China Ivory"),
    color!("#FCFFF9", "Ceramic"),
    color!("#FD0E35", "Torch Red"),
    color!("#FD5B78", "Wild Watermelon"),
    color!("#FD7B33", "Crusta"),
    color!("#FD7C07", "Sorbus"),
    color!("#FD9FA2", "Sweet Pink"),
    color!("#FDD5B1", "Light Apricot"),
    color!("#FDD7E4", "Pig Pink"),
    color!("#FDE1DC", "Cinderella"),
    color!("#FDE295", "Golden Glow"),
    color!("#FDE910", "Lemon"),
    color!("#FDF5E6", "Old Lace"),
    color!("#FDF6D3", "Half Colonial White"),
    color!("#FDF7AD", "Drover"),
    color!("#FDFEB8", "Pale Prim"),
    color!("#FDFFD5", "Cumulus"),
    color!("#FE28A2", "Persian Rose"),
    color!("#FE4C40", "Sunset Orange"),
    color!("#FE6F5E", "Bittersweet"),
    color!("#FE9D04", "California"),
    color!("#FEA904", "Yellow Sea"),
    color!("#FEBAAD", "Melon"),
    color!("#FED33C", "Bright Sun"),
    color!("#FED85D", "Dandelion"),
    color!("#FEDB8D", "Salomie"),
    color!("#FEE5AC", "Cape Honey"),
    color!("#FEEBF3", "Remy"),
    color!("#FEEFCE", "Oasis"),
    color!("#FEF0EC", "Bridesmaid"),
    color!("#FEF2C7", "Beeswax"),
    color!("#FEF3D8", "Bleach White"),
    color!("#FEF4CC", "Pipi"),
    color!("#FEF4DB", "Half Spanish White"),
    color!("#FEF4F8", "Wisp Pink"),
    color!("#FEF5F1", "Provincial Pink"),
    color!("#FEF7DE", "Half Dutch White"),
    color!("#FEF8E2", "Solitaire"),
    color!("#FEF8FF", "White Pointer"),
    color!("#FEF9E3", "Off Yellow"),
    color!("#FEFCED", "Orange White"),
    color!("#FF0000", "Red"),
    color!("#FF007F", "Rose"),
    color!("#FF00CC", "Purple Pizzazz"),
    color!("#FF00FF", "Magenta / Fuchsia"),
    color!("#FF2400", "Scarlet"),
    color!("#FF3399", "Wild Strawberry"),
    color!("#FF33CC", "Razzle Dazzle Rose"),
    color!("#FF355E", "Radical Red"),
    color!("#FF3F34", "Red Orange"),
    color!("#FF4040", "Coral Red"),
    color!("#FF4D00", "Vermilion"),
    color!("#FF4F00", "International Orange"),
    color!("#FF6037", "Outrageous Orange"),
    color!("#FF6600", "Blaze Orange"),
    color!("#FF66FF", "Pink Flamingo"),
    color!("#FF681F", "Orange"),
    color!("#FF69B4", "Hot Pink"),
    color!("#FF6B53", "Persimmon"),
    color!("#FF6FFF", "Blush Pink"),
    color!("#FF7034", "Burning Orange"),
    color!("#FF7518", "Pumpkin"),
    color!("#FF7D07", "Flamenco"),
    color!("#FF7F00", "Flush Orange"),
    color!("#FF7F50", "Coral"),
    color!("#FF8C69", "Salmon"),
    color!("#FF9000", "Pizazz"),
    color!("#FF910F", "West Side"),
    color!("#FF91A4", "Pink Salmon"),
    color!("#FF9933", "Neon Carrot"),
    color!("#FF9966", "Atomic Tangerine"),
    color!("#FF9980", "Vivid Tangerine"),
    color!("#FF9E2C", "Sunshade"),
    color!("#FFA000", "Orange Peel"),
    color!("#FFA194", "Mona Lisa"),
    color!("#FFA500", "Web Orange"),
    color!("#FFA6C9", "Carnation Pink"),
    color!("#FFAB81", "Hit Pink"),
    color!("#FFAE42", "Yellow Orange"),
    color!("#FFB0AC", "Cornflower Lilac"),
    color!("#FFB1B3", "Sundown"),
    color!("#FFB31F", "My Sin"),
    color!("#FFB555", "Texas Rose"),
    color!("#FFB7D5", "Cotton Candy"),
    color!("#FFB97B", "Macaroni and Cheese"),
    color!("#FFBA00", "Selective Yellow"),
    color!("#FFBD5F", "Koromiko"),
    color!("#FFBF00", "Amber"),
    color!("#FFC0A8", "Wax Flower"),
    color!("#FFC0CB", "Pink"),
    color!("#FFC3C0", "Your Pink"),
    color!("#FFC901", "Supernova"),
    color!("#FFCBA4", "Flesh"),
    color!("#FFCC33", "Sunglow"),
    color!("#FFCC5C", "Golden Tainoi"),
    color!("#FFCC99", "Peach Orange"),
    color!("#FFCD8C", "Chardonnay"),
    color!("#FFD1DC", "Pastel Pink"),
    color!("#FFD2B7", "Romantic"),
    color!("#FFD38C", "Grandis"),
    color!("#FFD700", "Gold"),
    color!("#FFD800", "School bus Yellow"),
    color!("#FFD8D9", "Cosmos"),
    color!("#FFDB58", "Mustard"),
    color!("#FFDCD6", "Peach Schnapps"),
    color!("#FFDDAF", "Caramel"),
    color!("#FFDDCD", "Tuft Bush"),
    color!("#FFDDCF", "Watusi"),
    color!("#FFDDF4", "Pink Lace"),
    color!("#FFDEAD", "Navajo White"),
    color!("#FFDEB3", "Frangipani"),
    color!("#FFE1DF", "Pippin"),
    color!("#FFE1F2", "Pale Rose"),
    color!("#FFE2C5", "Negroni"),
    color!("#FFE5A0", "Cream Brulee"),
    color!("#FFE5B4", "Peach"),
    color!("#FFE6C7", "Tequila"),
    color!("#FFE772", "Kournikova"),
    color!("#FFEAC8", "Sandy Beach"),
    color!("#FFEAD4", "Karry"),
    color!("#FFEC13", "Broom"),
    color!("#FFEDBC", "Colonial White"),
    color!("#FFEED8", "Derby"),
    color!("#FFEFA1", "Vis Vis"),
    color!("#FFEFC1", "Egg White"),
    color!("#FFEFD5", "Papaya Whip"),
    color!("#FFEFEC", "Fair Pink"),
    color!("#FFF0DB", "Peach Cream"),
    color!("#FFF0F5", "Lavender blush"),
    color!("#FFF14F", "Gorse"),
    color!("#FFF1B5", "Buttermilk"),
    color!("#FFF1D8", "Pink Lady"),
    color!("#FFF1EE", "Forget Me Not"),
    color!("#FFF1F9", "Tutu"),
    color!("#FFF39D", "Picasso"),
    color!("#FFF3F1", "Chardon"),
    color!("#FFF46E", "Paris Daisy"),
    color!("#FFF4CE", "Barley White"),
    color!("#FFF4DD", "Egg Sour"),
    color!("#FFF4E0", "Sazerac"),
    color!("#FFF4E8", "Serenade"),
    color!("#FFF4F3", "Chablis"),
    color!("#FFF5EE", "Seashell Peach"),
    color!("#FFF5F3", "Sauvignon"),
    color!("#FFF6D4", "Milk Punch"),
    color!("#FFF6DF", "Varden"),
    color!("#FFF6F5", "Rose White"),
    color!("#FFF8D1", "Baja White"),
    color!("#FFF9E2", "Gin Fizz"),
    color!("#FFF9E6", "Early Dawn"),
    color!("#FFFACD", "Lemon Chiffon"),
    color!("#FFFAF4", "Bridal Heath"),
    color!("#FFFBDC", "Scotch Mist"),
    color!("#FFFBF9", "Soapstone"),
    color!("#FFFC99", "Witch Haze"),
    color!("#FFFCEA", "Buttery White"),
    color!("#FFFCEE", "Island Spice"),
    color!("#FFFDD0", "Cream"),
    color!("#FFFDE6", "Chilean Heath"),
    color!("#FFFDE8", "Travertine"),
    color!("#FFFDF3", "Orchid White"),
    color!("#FFFDF4", "Quarter Pearl Lusta"),
    color!("#FFFEE1", "Half and Half"),
    color!("#FFFEEC", "Apricot White"),
    color!("#FFFEF0", "Rice Cake"),
    color!("#FFFEF6", "Black White"),
    color!("#FFFEFD", "Romance"),
    color!("#FFFF00", "Yellow"),
    color!("#FFFF66", "Laser Lemon"),
    color!("#FFFF99", "Pale Canary"),
    color!("#FFFFB4", "Portafino"),
    color!("#FFFFF0", "Ivory"),
    color!("#FFFFFF", "White"),
];
